(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   (quote
    (orgit org-projectile org-category-capture org-present alert log4e gntp org-download org-brain htmlize evil-org smeargle magit-gitflow helm-gitignore magit magit-popup git-commit with-editor dash async names chinese-word-at-point pyim pyim-basedict pos-tip pinyinlib volatile-highlights vi-tilde-fringe symon string-inflection spaceline powerline rainbow-delimiters password-generator org-bullets lorem-ipsum highlight-indentation helm-themes helm-swoop helm-purpose window-purpose imenu-list helm-projectile helm-mode-manager helm-make helm-flx helm-descbinds google-translate flx-ido fancy-battery eyebrowse evil-unimpaired evil-mc evil-lisp-state smartparens evil-lion evil-indent-plus evil-exchange evil-escape evil-ediff evil-args editorconfig define-word clean-aindent-mode ace-jump-helm-line youdao-dictionary xterm-color ws-butler wrap-region winum which-key wgrep web-mode visual-regexp-steroids uuidgen use-package unfill toc-org tiny tagedit solarized-theme smex slim-mode sicp shell-pop scss-mode sass-mode reveal-in-osx-finder restart-emacs ranger rainbow-mode rainbow-identifiers racket-mode pug-mode prodigy popwin persp-mode peep-dired pcre2el pbcopy paredit paradox pangu-spacing osx-trash osx-dictionary origami org-pomodoro org-plus-contrib open-junk-file nodejs-repl neotree mwim multiple-cursors multi-term move-text mmm-mode markdown-toc macrostep lispy linum-relative link-hint less-css-mode launchctl ivy-hydra info+ indent-guide impatient-mode ibuffer-projectile hungry-delete hl-todo highlight-parentheses highlight-numbers highlight-global hide-comnt help-fns+ helm-github-stars helm-ag graphviz-dot-mode golden-ratio gnuplot gitignore-mode github-search github-clone gitconfig-mode gitattributes-mode git-timemachine git-messenger git-link git-gutter-fringe+ gist ggtags fuzzy flyspell-correct-ivy flycheck-pos-tip flx find-file-in-project find-by-pinyin-dired fill-column-indicator expand-region exec-path-from-shell evil-visualstar evil-visual-mark-mode evil-tutor evil-surround evil-search-highlight-persist evil-numbers evil-nerd-commenter evil-matchit evil-magit evil-iedit-state evil-anzu eval-sexp-fu etags-select eshell-z eshell-prompt-extras esh-help engine-mode emmet-mode elisp-slime-nav dumb-jump discover-my-major diff-hl deft counsel company-web company-statistics column-enforce-mode color-identifiers-mode cmake-font-lock chinese-pyim browse-at-remote boxquote bind-map bbdb auto-yasnippet auto-highlight-symbol auto-compile aggressive-indent adaptive-wrap ace-pinyin ace-link 4clojure))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
